#
# IMPORTANT NOTE
#
# This chart inherits from the common library chart. You can check the default values/options here:
# https://github.com/johanneskastl/helm-charts/tree/main/charts/common/values.yaml
#

image:
  # -- image repository
  repository: tremolosecurity/apacheds
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

controller:
  type: statefulset

serviceAccount:
  create: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: true
    type: LoadBalancer
    ports:
      http:
        enabled: false
      ldap-tcp:
        enabled: true
        port: 389
        protocol: TCP
        targetPort: 10389
      ldap-udp:
        enabled: false
        port: 389
        protocol: UDP
        targetPort: 10389
      ldaps-tcp:
        enabled: true
        port: 636
        protocol: TCP
        targetPort: 10636
      ldaps-udp:
        enabled: false
        port: 636
        protocol: UDP
        targetPort: 10636

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Use environment variables from the apacheds-configuration secret
# @default -- See values.yaml
envFrom:
  - secretRef:
      name: apacheds-configuration

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # -- For persistence, you should have your JAVA keystore stored in Kubernetes in a secret and mounted into the pod. To do that set the `persistence.config.name` key to the name of your existing secret in your values.yaml file.
  # @default -- See below
  config:
    # -- Currently the container image does not work without the keystore secret, so do NOT disable this
    enabled: true
    # -- The keystore files needs to end up in /etc/apacheds/apacheds.jks
    mountPath: /etc/apacheds/
    type: secret
    readOnly: true
  # -- Persistence for the application data
  # @default -- See below
  data:
    # -- You normally want persistence for the LDAP data. Disable at your own peril...
    enabled: true
    # -- ApacheDS writes the data to /var/apacheds/
    mountPath: /var/apacheds/
    # -- There should only be one pod writing to the volume
    accessMode: ReadWriteOnce
    # -- Setting this to readOnly does not make sense
    readOnly: false
    # -- Do not delete the volume if the helm chart is being uninstalled, to prevent data loss...
    retain: true
  # -- Set this to enabled if you want to import files from a secret. Then set `persistence.ldifimport.name` to the name of your Kubernetes secret in your values.yaml file.
  # @default -- See below
  ldifimport:
    # -- Set this to true if you want to enable the import from a LDIF file
    enabled: false
    # -- You should store the LDIF information in a secret
    type: secret
    # -- The container image expects the LDIF file to import to be in /etc/apacheds-data/data.ldif
    mountPath: /etc/apacheds-data/

probes:
  liveness:
    enabled: true
    spec:
      tcpSocket:
        port: 10389
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 1
      failureThreshold: 3
  readiness:
    enabled: true
    spec:
      tcpSocket:
        port: 10389
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 1
      failureThreshold: 3
  startup:
    enabled: true
    spec:
      tcpSocket:
        port: 10389
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 12

# -- Set the resource requests / limits for the main container.
# @default -- See below
resources:
  # -- resource limits for the pod
  # @default -- See below
  limits:
    # -- cpu limit
    cpu: 250m
    # -- memory limit
    memory: 256Mi
  # -- resource requests for the pod
  # @default -- See below
  requests:
    # -- cpu request
    cpu: 125m
    # -- memory request
    memory: 128Mi
