{{/* Make sure all variables are set properly */}}
{{- include "common.values.setup" . }}

{{/* Append the hardcoded settings */}}
{{- define "openldap.hardcodedValues" -}}
env:
  {{ if .Values.persistence.ldifimport.enabled }}
    LDAP_SKIP_DEFAULT_TREE: 'no'
    LDAP_CUSTOM_LDIF_DIR: '/ldif_import/'
  {{ end }}
  {{ if .Values.persistence.certificate.enabled }}
    LDAP_ENABLE_TLS: 'yes'
    LDAP_TLS_CERT_FILE: '/etc/ssl/private/tls.crt'
    LDAP_TLS_KEY_FILE: '/etc/ssl/private/tls.key'
    LDAP_TLS_CA_FILE: '/etc/ssl/private/tls.crt'
  {{ else }}
    LDAP_ENABLE_TLS: 'no'
  {{ end }}
      {{- end -}}
    {{- $_ := mergeOverwrite .Values (include "openldap.hardcodedValues" . | fromYaml) -}}

    {{/* Render the templates */}}
{{ include "common.all" . }}
